### ISSUE TITLE
improvement of react / angular 

### ISSUE THREAD

**Issue by JSXRED** [PeterNgTr/codeceptjs-chrome-recorder#1]
first of all: FINALLY! - i am super happy about this project :)

many frameworks based on react / angular work with "data-automation-id"-attribute, which is automatically added to the elements. especially react often generates dynamic id/css classes which are changing after each build and this causes problems, which is why there is the data-automation-id.

is it possible to prioritise data-automation-id or are pull requests desired?

**Comment by kobenguyent** [comment]
hi @JSXRED thanks for your report! If you already had idea for PR, that'll be great to see!

**Comment by JSXRED** [comment]
I haven't made a pull request yet, but I have had a look at the code and tried out a few things. I think only the selectors would have to be extended for this.  If you manually add data-automation-id to "SELECTOR ATTRIBUTE" in the configuration of the recording, then it works as wished. It is just stupid to have to do this every time and if you have mix of different attributes.

**Common selectors from frameworks as I know are:**
* data-testid  
* data-test  
* data-test-id  
* data-qa  
* data-cy  
* data-qa-id  
* data-testing  
* data-automation-id  
* data-automationId

So may they can be added by default configuration of selectors.

**Comment by kobenguyent** [comment]
well, I could be wrong but per my understanding, the selector attribute is from the recorder which is before the code generator https://developer.chrome.com/docs/devtools/recorder/reference#selector. Having said that, I think we could do nothing than adding your selector attribute yourself when recording the steps. Hence, I'd close this ticket.
![Screenshot 2023-12-06 at 09 49 39](https://github.com/kobenguyent/codeceptjs-chrome-recorder/assets/7845001/b3163541-3b5d-4d22-bc02-8cc6e9b5617a)
