### ISSUE TITLE
Extension not shown in Microsoft Edge

### ISSUE THREAD

**Issue by JSXRED** [PeterNgTr/codeceptjs-chrome-recorder#2]
You can install the extension in Microsoft Edge, but "Recorder" is not shown in Microsoft Edge (Chrome Version). 
![image](https://github.com/kobenguyent/codeceptjs-chrome-recorder/assets/10437799/92f3b3b0-7c08-4db4-9f1a-4319db27180d)

**Comment by kobenguyent** [comment]
I think that's expected! As Recorder is only exclusively available for Chrome!
